using OnlineMuhasebeServer.Domain.AppEntities;
using OnlineMuhasebeServer.Domain.Repositories.GenericRepository.AppDbContext;

namespace OnlineMuhasebeServer.Domain.Repositories.AppDbContext.MainRoleAndRoleRelationshipRepositories;

public interface IMainRoleAndRoleRelationshipQueryRepository : IAppQueryRepository<MainRoleAndRoleRelationship>
{

}
