using OnlineMuhasebeServer.Domain.AppEntities;
using OnlineMuhasebeServer.Domain.Repositories.GenericRepository.AppDbContext;

namespace OnlineMuhasebeServer.Domain.Repositories.AppDbContext.MainRoleAndRoleRelationshipRepositories;

public interface IMainRoleAndRoleRelationshipCommandRepository : IAppCommandRepository<MainRoleAndRoleRelationship>
{

}
