using OnlineMuhasebeServer.Domain.AppEntities;
using OnlineMuhasebeServer.Domain.Repositories.GenericRepository.AppDbContext;


namespace OnlineMuhasebeServer.Domain.Repositories.AppDbContext.MainRoleAndUserRelationshipRepositories;

public interface IMainRoleAndUserRelationshipQueryRepository : IAppQueryRepository<MainRoleAndUserRelationship>
{

}
